NUMPY.

1.

In [2]:
import numpy as np
A = np.logspace(-3,7,200).reshape(10,5,4)
print(A[3,0,2])
print(A[5,4,1])
print(A[-1,-1,-1])

1.3049019780144029
757.525025877192
10000000.0


In [3]:
B = np.array([[-2,8,10,1],[17,9,2,0],[1,6,-4,10],[3,8,-9,4]])
B[B > 4] = 4
print(B)

[[-2  4  4  1]
 [ 4  4  2  0]
 [ 1  4 -4  4]
 [ 3  4 -9  4]]


In [4]:
C = np.zeros((10,10))
C[::2, ::2] = 1
print(C)

[[1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


2.

In [7]:
import numpy.random as npr
x = np.sort(npr.rand(100))
y = np.sort(npr.rand(100))

In [9]:
xx,yy = np.meshgrid(x,y)
z = np.exp(-(np.sqrt(xx)+ np.sqrt(yy))/(0.05))

MATPLOTLIB.

1.